
credits = {
    "",
    "Dough",
    "For",
    "Dreams",
    "",
    "Programmed by Bryce McWhirter",
    "",
    "Art by Gabby McWhirter",
    "",
    "Music: ",
    "Background music by Jan Hehr",
    "https://janhehr.com",
     "",
     "Tracks Include: ",
    "Autumn Leaves",
    "Blithe",
    "Closed Bakery",
    "Good Old Days",
    "My Only Love",
    "Till Death Do Us Part",
    "",
    "Special Thanks:",
    "Penny McWhirter",
    "Arty McWhirter",
    "",
    "Built with LÖVE2D",
    "",
    "",
    "",
    "",
    "Thank you for playing!",
    "",
    ""
}
